export const SHOWREEL_YT_ID = "u0dBG0AL3Cs";

export const PIECES_GENRES = [
  "Piano",
  "Orchestral",
  "Vintage",
  "Electronic",
  "Folkish",
  "Lyrics",
  "No lyrics",
  "Epic",
  "Easy",
  "Eccentric",
  "Intense",
  "Smooth",
  "Translucent",
  "Vibrant",
  "Misty",
  "Dark",
];

export const PROJECTS_GENRES = [
  "Film",
  "Commercial",
  "Video Game",
  "Fantasy",
  "Mystery",
  "Thriller",
  "Drama",
  "Art",
  "Comedy",
  "Action",
];

export const PIECES = [
  {
    title: "Solnechno",
    tags: ["Piano", "Lyrics", "Vibrant", "Translucent"],
    image: "/images/pieces/solnechno.webp",
    audio: "/audio/solnechno.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "Day In May",
    tags: ["Lyrics", "Piano", "Smooth", "Vibrant"],
    image: "/images/pieces/day-in-may.webp",
    audio: "/audio/day-in-may.mp3",
    video: "7Xg8likIl5k",
  },
  {
    title: "Tomorrow",
    tags: ["Eccentric", "Vibrant", "Epic", "Lyrics", "Piano", "Orchestral"],
    image: "/images/pieces/tomorrow.webp",
    audio: "/audio/tomorrow.mp3",
    video: "MrHxTiygKts",
  },

  {
    title: "Plavno",
    tags: [
      "Eccentric",
      "Intense",
      "Vibrant",
      "Epic",
      "Folkish",
      "Lyrics",
      "Piano",
      "Orchestral",
    ],
    image: "/images/pieces/plavno.webp",
    audio: "/audio/plavno.mp3",
    video: "A39qBuer1T4",
  },
  {
    title: "Piano Play",
    tags: ["No lyrics", "Intense", "Dark", "Misty", "Piano", "Orchestral"],
    image: "/images/pieces/piano-play.webp",
    audio: "/audio/piano-play.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "People made of rocks",
    tags: ["Piano", "Lyrics", "Orchestral", "Misty", "Translucent", "Epic"],
    image: "/images/pieces/people-made-of-rocks.webp",
    audio: "/audio/people-made-of-rocks.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "The End Of Patiance",
    tags: ["No lyrics", "Intense", "Misty", "Piano"],
    image: "/images/pieces/the-end-of-patiance.webp",
    audio: "/audio/the-end-of-patience.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "Cats and Dogs",
    tags: ["Dark", "Misty", "No lyrics", "Vintage"],
    image: "/images/pieces/cats-and-dogs.webp",
    audio: "/audio/cats-and-dogs.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "Dance Ballet",
    tags: ["Easy", "Folkish", "Lyrics", "Vibrant"],
    image: "/images/pieces/dance-ballet.webp",
    audio: "/audio/dance-ballet.mp3",
    video: "_m8Im8d2Lnk",
  },
  {
    title: "Death And Stuff",
    tags: ["Lyrics", "Piano", "Smooth", "Vibrant"],
    image: "/images/pieces/death-and-stuff.webp",
    audio: "/audio/death-and-stuff.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "Dumb Go Down",
    tags: ["Lyrics", "Piano", "Smooth", "Vibrant"],
    image: "/images/pieces/dumb-go-down.webp",
    audio: "/audio/dumb-go-down.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "Eldorado",
    tags: ["Lyrics", "Piano", "Smooth", "Vibrant"],
    image: "/images/pieces/eldorado.webp",
    audio: "/audio/eldorado.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "Everyman's Thoughts",
    tags: ["No lyrics", "Misty", "Smooth", "Piano"],
    image: "/images/pieces/everymans-thoughts.webp",
    audio: "/audio/everymens-thoughts.mp3",
    video: "F3ix2q9BCrU",
  },
  {
    title: "Full Of Wondering",
    tags: ["No lyrics", "Misty", "Electronic", "Piano", "Smooth"],
    image: "/images/pieces/full-of-wondering.webp",
    audio: "/audio/full-of-wodering.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "Going Far Away",
    tags: ["Lyrics", "Folkish", "Vintage", "Misty", "Easy"],
    image: "/images/pieces/going-far-away.webp",
    audio: "/audio/going-far-away.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "I Don't know",
    tags: ["Eccentric", "Vibrant", "Folkish", "Lyrics", "Piano"],
    image: "/images/pieces/i-dont-know.webp",
    audio: "/audio/i-dont-know.mp3",
    video: "MrHxTiygKts",
  },
  {
    title: "I Thought It Would Be fun",
    tags: ["Smooth", "Translucent", "Lyrics", "Piano"],
    image: "/images/pieces/i-thought-it-would-be-fun.webp",
    audio: "/audio/i-thought-it-would-be-fun.mp3",
    video: "A3FFk9WAqt0",
  },
  {
    title: "Journey Around The Fortune",
    tags: ["No lyrics", "Intense", "Misty", "Easy", "Folkish", "Vintage"],
    image: "/images/pieces/journey-around-the-fortune.webp",
    audio: "/audio/journey-around-the-fortune.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "Places",
    tags: ["No lyrics", "Intense", "Dark", "Misty", "Piano", "Orchestral"],
    image: "/images/pieces/places.webp",
    audio: "/audio/places.mp3",
    video: "9u8eCQSS-qk",
  },

  {
    title: "Power Drip",
    tags: [
      "Electronic",
      "No lyrics",
      "Misty",
      "Smooth",
      "Translucent",
      "Piano",
      "Orchestral",
      "Vibrant",
    ],
    image: "/images/pieces/power-drip.webp",
    audio: "/audio/power-drip.mp3",
    video: "SeLDca5TCw8",
  },
  {
    title: "Pulse",
    tags: [
      "Eccentric",
      "Vibrant",
      "Folkish",
      "Easy",
      "Lyrics",
      "Orchestral",
      "Vintage",
    ],
    image: "/images/pieces/pulse.webp",
    audio: "/audio/pulse.mp3",
    video: "2gngOKKHxFs",
  },
  {
    title: "Rain And Wind",
    tags: ["No lyrics", "Intense", "Dark", "Misty", "Piano", "Orchestral"],
    image: "/images/pieces/rain-and-wind.webp",
    audio: "/audio/rain-and-wind.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "Bezhat",
    tags: ["Lyrics", "Eccentric", "Vibrant"],
    image: "/images/pieces/bezhat.webp",
    audio: "/audio/bezhat.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "Revival Of The Unknown",
    tags: ["No lyrics", "Epic", "Vibrant", "Dark", "Orchestral"],
    image: "/images/pieces/revival-of-the-unknown.webp",
    audio: "/audio/revival-of-the-unknown.mp3",
    video: "tFB_pqg_HTY",
  },
  {
    title: "Soon",
    tags: ["Electronic", "Misty", "Easy", "Smooth", "Translucent", "Lyrics"],
    image: "/images/pieces/soon.webp",
    audio: "/audio/skoro.mp3",
    video: "y3-9oUOCoKM",
  },
  {
    title: "Threat Serenade",
    tags: [
      "Electronic",
      "No lyrics",
      "Eccentric",
      "Intense",
      "Dark",
      "Misty",
      "Orchestral",
    ],
    image: "/images/pieces/threat-serenade.webp",
    audio: "/audio/threat-serenade.mp3",
    video: SHOWREEL_YT_ID,
  },
  {
    title: "Worn Out",
    tags: ["Dark", "Misty", "No lyrics", "Vintage"],
    image: "/images/pieces/worn-out.webp",
    audio: "/audio/worn-out.mp3",
    video: SHOWREEL_YT_ID,
  },
];

export const PROJECTS = [
  {
    name: "Six Empty Seats",
    genre: "TV Drama",
    year: "2021",
    tags: ["Film", "Drama", "Mystery", "Action", "Thriller"],
    image: "/images/projects/six-empty-seats.webp",
    video: SHOWREEL_YT_ID,
    tracks: [
      {
        name: "Confusion",
        audio: "/audio/confusion.mp3",
        duration: "1:46",
      },
      {
        name: "Desolation",
        audio: "/audio/desolation.mp3",
        duration: "0:45",
      },
    ],
  },
  {
    name: "The Teachers",
    genre: "TV Drama",
    year: "2019",
    tags: ["Film", "Drama"],
    image: "/images/projects/teachers.webp",
    video: SHOWREEL_YT_ID,
    tracks: [
      {
        name: "Long Happy Life (by GROB)",
        audio: "/audio/long-happy-life-by-grob.mp3",
        duration: "1:16",
      },
      {
        name: "Moya Oborona (by GROB)",
        audio: "/audio/moya-oborona-by-grob.mp3",
        duration: "1:16",
      },
      {
        name: "Realisation",
        audio: "/audio/realisation.mp3",
        duration: "1:16",
      },
      {
        name: "Turn Of Events",
        audio: "/audio/turn-of-events.mp3",
        duration: "2:57",
      },
    ],
  },
  {
    name: "Call Center",
    genre: "TV Series",
    year: "2020",
    tags: ["Film", "Drama", "Mystery", "Action", "Thriller"],
    image: "/images/projects/call-center.webp",
    video: SHOWREEL_YT_ID,
    tracks: [
      {
        name: "Count Down",
        audio: "/audio/count-down.mp3",
        duration: "0:11",
      },
      {
        name: "Into Action",
        audio: "/audio/into-action.mp3",
        duration: "2:39",
      },
      {
        name: "Unfixable",
        audio: "/audio/unfixible.mp3",
        duration: "1:51",
      },
      {
        name: "Rejection",
        audio: "/audio/rejection.mp3",
        duration: "0:56",
      },
      {
        name: "Over",
        audio: "/audio/over.mp3",
        duration: "2:07",
      },
    ],
  },
  {
    name: "Scrunchie",
    genre: "Film",
    year: "2021",
    tags: ["Film", "Drama", "Comedy"],
    image: "/images/projects/scrunchie.webp",
    video: SHOWREEL_YT_ID,
    tracks: [
      {
        name: "Attraction",
        audio: "/audio/attraction.mp3",
        duration: "1:34",
      },
      {
        name: "Passion",
        audio: "/audio/passion.mp3",
        duration: "1:09",
      },
    ],
  },
  {
    name: "To The Lake",
    genre: "Film",
    year: "2019",
    tags: ["Film", "Drama", "Action", "Thriller"],
    image: "/images/projects/to-the-lake.webp",
    video: SHOWREEL_YT_ID,
    tracks: [
      {
        name: "Keep It Low",
        audio: "/audio/keep-it-low.mp3",
        duration: "1:15",
      },
      {
        name: "Danger Alert",
        audio: "/audio/danger-alert.mp3",
        duration: "0:56",
      },
    ],
  },
  {
    name: "Exclusion Zone",
    genre: "TV Series",
    year: "2019",
    tags: ["Film", "Drama", "Mystery", "Action", "Fantasy"],
    image: "/images/projects/exclusion-zone.webp",
    video: SHOWREEL_YT_ID,
    tracks: [
      {
        name: "Never",
        audio: "/audio/never.mp3",
        duration: "2:46",
      },
    ],
  },
  {
    name: "Horizon",
    genre: "TV Series",
    year: "2020",
    tags: ["Film", "Drama", "Mystery", "Action", "Thriller"],
    image: "/images/projects/horizon.webp",
    video: SHOWREEL_YT_ID,
    tracks: [
      {
        name: "Closer to the light",
        audio: "/audio/closer-to-the-light.mp3",
        duration: "0:32",
      },
      {
        name: "Distorted",
        audio: "/audio/distorted.mp3",
        duration: "0:42",
      },
      {
        name: "Relief",
        audio: "/audio/relief.mp3",
        duration: "1:58",
      },
    ],
  },
  {
    name: "One Day More",
    genre: "Video Game",
    year: "2021",
    tags: ["Video Game", "Fantasy", "Art", "Comedy"],
    image: "/images/projects/one-day-more.webp",
    video: "gJ9TwQn8awc",
    tracks: [
      {
        name: "Rehearsals",
        audio: "/audio/rehearsals.mp3",
        duration: "1:00",
      },
      {
        name: "Fantasy Afternoon",
        audio: "/audio/fantasy-afternoon.mp3",
        duration: "0:59",
      },
      {
        name: "Rush",
        audio: "/audio/rush.mp3",
        duration: "1:26",
      },
      {
        name: "Shadow Upon All",
        audio: "/audio/shadow-upon-all.mp3",
        duration: "3:05",
      },
      {
        name: "Electrification",
        audio: "/audio/electification.mp3",
        duration: "0:58",
      },
      {
        name: "Crispy Streets",
        audio: "/audio/crispy-streets.mp3",
        duration: "2:05",
      },
      {
        name: "Naive Sunlight",
        audio: "/audio/naive-sunlight.mp3",
        duration: "1:50",
      },
      {
        name: "See Ya",
        audio: "/audio/see-ya.mp3",
        duration: "1:48",
      },
      {
        name: "Woops",
        audio: "/audio/woops.mp3",
        duration: "1:38",
      },
    ],
  },
  {
    name: "Trains",
    genre: "Video Game",
    year: "2024",
    tags: ["Video Game", "Mystery", "Action", "Fantasy"],
    image: "/images/projects/trains.webp",
    video: "Mf5iJuDOZQw",
    tracks: [
      {
        name: "Pain Killer",
        audio: "/audio/pain-killer.mp3",
        duration: "0:47",
      },
    ],
  },
  {
    name: "Disha Zhang's Showcase",
    genre: "Dance Show Trailer",
    year: "2018",
    tags: ["Commercial", "Art", "Comedy"],
    image: "/images/projects/disha-zhangs.webp",
    video: "DEJJk2ZAh48",
    tracks: [
      {
        name: "Laundry Day",
        audio: "/audio/laundry-day.mp3",
        duration: "1:21",
      },
    ],
  },
  {
    name: "Solomon's Showcase",
    genre: "Dance Show Trailer",
    year: "2018",
    tags: ["Commercial", "Drama", "Art"],
    image: "/images/projects/solomon.webp",
    video: "_tZlL1URPSM",
    tracks: [
      {
        name: "Slow and Curious",
        audio: "/audio/slow-and-curious.mp3",
        duration: "1:58",
      },
    ],
  },
  {
    name: "Intersection Point",
    genre: "Dance Show Trailer",
    year: "2017",
    tags: ["Commercial", "Drama", "Art", "Action"],
    image: "/images/projects/intersection-point.webp",
    video: "s9qQPGEb1Bg",
    tracks: [
      {
        name: "Intersection Point",
        audio: "/audio/intersection-point.mp3",
        duration: "0:59",
      },
    ],
  },
  {
    name: "ProTrener",
    genre: "Commercial",
    year: "2021",
    tags: ["Commercial", "Action"],
    image: "/images/projects/protrener.webp",
    video: "2yrESIMpcOc",
    tracks: [
      {
        name: "Breakthrough",
        audio: "/audio/breakthrough.mp3",
        duration: "5:23",
      },
      {
        name: "Crunchy",
        audio: "/audio/crunchy.mp3",
        duration: "3:18",
      },
      {
        name: "Step By Step",
        audio: "/audio/step-by-step.mp3",
        duration: "2:56",
      },
      {
        name: "Wake Up",
        audio: "/audio/wake-up.mp3",
        duration: "2:10",
      },
      {
        name: "Workout Season",
        audio: "/audio/workout-season.mp3",
        duration: "1:32",
      },
    ],
  },
  {
    name: "Ikea",
    genre: "Commercial",
    year: "2014, 2018",
    tags: ["Commercial", "Comedy"],
    image: "/images/projects/ikea.webp",
    video: "M9TZrDk7VCFyR4mG",
    tracks: [
      {
        name: "Don't You Dare",
        audio: "/audio/don't-you-dare.mp3",
        duration: "0:31",
      },
      {
        name: "Sunflakes",
        audio: "/audio/sunflakes.mp3",
        duration: "4:42",
      },
    ],
  },
  {
    name: "Marsh",
    genre: "Commercial",
    year: "2016",
    tags: ["Commercial", "Action", "Art"],
    image: "/images/projects/marsh.webp",
    video: "BbGFUthSN9U",
    tracks: [
      {
        name: "Blib",
        audio: "/audio/blip.mp3",
        duration: "1:12",
      },
    ],
  },
];

export const HOME_BACKGROUND_IMAGES = [
  {
    mobile: "/images/home/flower1_414x753.webp",
    desktop: "/images/home/flower1_2180x1634.webp",
  },
  {
    mobile: "/images/home/flower2_414x753.webp",
    desktop: "/images/home/flower2_2180x1634.webp",
  },
  {
    mobile: "/images/home/flower3_414x753.webp",
    desktop: "/images/home/flower3_2180x1634.webp",
  },
];
