name: Deploy to Production Server

# Запускать этот workflow при каждом пуше в ветку main
on:
  push:
    branches:
      - main

jobs:
  # Новое задание: запустить скриншот-тесты
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Устанавливаем Node.js, используя версию из .nvmrc
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm ci

      # 4. Запускаем скриншот-тесты Chromatic
      - name: Run Chromatic Screenshot Tests
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: npx chromatic

  # Задание для сборки (теперь зависит от тестов)
  build-and-update-image:
    needs: test # <--- Запускается только после успешного прохождения тестов
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Логинимся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Собираем и отправляем образ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          push: true
          tags: peterlipatov/composer-v2-production:latest

  # Задание для деплоя (зависимости не изменились)
  deploy-on-server:
    needs: build-and-update-image
    runs-on: ubuntu-latest
    steps:
      # 1. Подключаемся к серверу по SSH и выполняем команды
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/liza-app
            docker pull peterlipatov/composer-v2-production:latest
            docker compose up -d
            echo "Deployment finished successfully!"
